config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

    resources :blogs, :recipes, :reviews, :activities

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :master, polymorphic: true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	has_many :activities, as: :master
	validates :title, presence: true,
                    length: { minimum: 5 }

                    after_create do |blog|
                    	Activity.create(master_id: blog.id, master_type: blog.class.name)
                 
                    end

                    after_update do |blog|
                    	Activity.create(master_id: blog.id, master_type: blog.class.name)
                    	end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	has_many :activities, as: :master

        after_create do |recipe|
    	Activity.create(master_id: recipe.id, master_type: recipe.class.name)
  
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	has_many :activities, as: :master

	                    after_create do |review|
                    	Activity.create(master_id: review.id, master_type: review.class.name)
                 
                    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :blogs
         has_many :reviews
         has_many :recipes
         has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
  	@activities = Activity.all
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	before_action :authenticate_user!

	def index
		@blogs = Blog.where(user_id: current_user.id)
	end



	def show
		@blog = Blog.find(params[:id])
	end



	def new
		@article = Blog.new
	end



	def edit
  		@blog = Blog.find(params[:id])
	end

	

	def create
		@blog = Blog.new(blog_params)
 		@blog.user_id = current_user.id
		if @blog.save
		  redirect_to @blog
		else
			render 'new'
		end
	end


	def update
	  @blog = Blog.find(params[:id])
	 
	  if @blog.update(blog_params)
	    redirect_to @blog
	  else
	    render 'edit'
	  end
	end



	def destroy
	  @blog = Blog.find(params[:id])
	  @blog.destroy
	 
	  redirect_to blogs_path
	end




	private

	def blog_params
		params.require(:blog).permit(:title, :text, )
	end
	
end


 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@recipes = Recipe.where(user_id: current_user.id)
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe = Recipe.new ## why didn't this need any method body to work?
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe = Recipe.new(recipe_params)
 		@recipe.user_id = current_user.id
		if @recipe.save
		  redirect_to @recipe
		else
			render 'new'
		end
	end

	def update
	  @recipe = Recipe.find(params[:id])
	 
	  if @recipe.update(recipe_params)
	    redirect_to @recipe
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @recipe = Recipe.find(params[:id])
	  @recipe.destroy
	 
	  redirect_to recipes_path
	end






	private

	def recipe_params
		params.require(:recipe).permit(:name, :text)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@reviews = Review.all
	end



	def show
		@review = Review.find(params[:id])
	end



	def new
		@review = Review.new
	end


	def edit
		@review = Review.find(params[:id])
	end


	def create
		@review = Review.new(review_params)
 		@review.user_id = current_user.id
		if @review.save
		  redirect_to @review
		else
			render 'new'
		end
	end



	def update
		@review = Review.find(params[:id])

		if @review.update(review_params)
			redirect_to @review
		else
			render 'edit'
		end
	end


	def destroy
	  @review = Blog.find(params[:id])
	  @review.destroy
	 
	  redirect_to reviews_path
	end

	

	private

	def review_params
		params.require(:review).permit(:title, :text)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/index.html.erb
<h1>Activities#index</h1>
<% @activities.each do |activity| %>
	<td><%= activity.master_id %> </td>
	<td><%= activity.master_type %></td>
	<tb><%= activity.master.user.email %><td>
	<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>
 
<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>SousBLOG</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.text %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
       <td><%= link_to 'Destroy', blog_path(blog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> 
            </td>
    </tr>
  <% end %>
   <%= link_to 'New Blog', new_blog_path %>
</table>

app/views/blogs/new.html.erb
<%= form_for :blog, url: blogs_path do |b| %>
  <p>
    <%= b.label :title %><br>
    <%= b.text_field :title %>
  </p>
 
  <p>
    <%= b.label :text %><br>
    <%= b.text_area :text %>
  </p>
 
  <p>
    <%= b.submit %>
  </p>

  <%= link_to 'New Blog', new_blog_path %>
  <%= link_to 'Back', blogs_path %>

<% end %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>

<%= link_to 'Back', blogs_path %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blog_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sous</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</html>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>
 
<%= form_for :recipe, url: recipe_path(@recipe), method: :patch do |r| %>

  <p>
    <%= r.label :name %><br>
    <%= r.text_field :name%>
  </p>
 
  <p>
    <%= r.label :text %><br>
    <%= r.text_area :text %>
  </p>
 
  <p>
    <%= r.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>SousRECIPE</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Instructions</th>
  </tr>
 
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.text %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
       <td><%= link_to 'Destroy', recipes_path(recipe),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
   <%= link_to 'New Recipe', new_recipe_path %>
</table>

app/views/recipes/new.html.erb
<%= form_for :recipe, url: recipes_path do |r| %>
  <p>
    <%= r.label :name %><br>
    <%= r.text_field :name %>
  </p>
 
  <p>
    <%= r.label :text %><br>
    <%= r.text_area :text %>
  </p>
 
  <p>
    <%= r.submit %>
  </p>

  <%= link_to 'New Recipe', new_recipe_path %>
  <%= link_to 'Back', recipes_path %>

<% end %>

app/views/recipes/show.html.erb
<p>
  <strong>Recipe Name:</strong>
  <%= @recipe.name %>
</p>
 
<p>
  <strong>Instructions:</strong>
  <%= @recipe.text %>
</p>

<%= link_to 'Back', recipes_path %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>
 
<%= form_for :review, url: review_path(@review), method: :patch do |r| %>

  <p>
    <%= r.label :title %><br>
    <%= r.text_field :title%>
  </p>
 
  <p>
    <%= r.label :text %><br>
    <%= r.text_area :text %>
  </p>
 
  <p>
    <%= r.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>SousREVIEW</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
      <td><%= link_to 'Edit', edit_review_path(review) %></td>
       <td><%= link_to 'Destroy', review_path(review),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> 
            </td>
    </tr>
  <% end %>
   <%= link_to 'New Review', new_review_path %>
</table>

app/views/reviews/new.html.erb
<%= form_for :review, url: reviews_path do |r| %>
  <p>
    <%= r.label :title %><br>
    <%= r.text_field :title %>
  </p>
 
  <p>
    <%= r.label :text %><br>
    <%= r.text_area :text %>
  </p>
 
  <p>
    <%= r.submit %>
  </p>

  <%= link_to 'New Review', new_review_path %>
  <%= link_to 'Back', reviews_path %>

<% end %>

app/views/reviews/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>

<%= link_to 'Back', reviews_path %>

app/views/welcome/index.html.erb
<h1>Bonjour! Welcome to Sous!</h1>


<%= link_to 'My Blog', controller: 'blogs' %>
<%= link_to 'My Recipes', controller: 'recipes' %>
<%= link_to 'My Reviews', controller: 'reviews' %>